### PR TITLE
Issue/46: Misaligned Secondary section and other fixes

### LINKED ISSUE #46: Secondary feature is mis-aligned
Figma:

Screenshot 2021-06-28 at 12 45 52

Current alignment via Vercel:

Screenshot 2021-06-28 at 12 46 23

### PR DESCRIPTION
**Pull request by dasilvaluis**
### What does it fix?

Closes #46  

- Fixes alignments with site container on Features section as described in #46 
- Fixes similar issue on Cards section
- Make Cards section present both parts in a row in lg and xl screens
- Make site container have a maxWidth of `1180px` as shown in Figma

### How has it been tested?

image

image

image

image

### CODE REVIEW

File: src/home/cards/b-card/about/title.jsx [hunk 1]
```diff
@@ -4,6 +4,8 @@ import { Typography } from '@mui/material'
 
 const useStyles = makeStyles({ root: { fontWeight: 700 } })
 
-export const Title = () => <Typography variant={'h5'} className={useStyles().root}>
-  Cursuri zilnice de cateva minute
-</Typography>
+export const Title = () => (
+  <Typography variant={'h5'} className={useStyles().root}>
+    Cursuri zilnice de cateva minute
```
Comment (andreiio) [inline src/home/cards/b-card/about/title.jsx]:
```suggestion
    Cursuri zilnice de câteva minute
```

**Review by andreiio — APPROVED** [review]
